### PR TITLE
Shortcode abstraction

### PR DESCRIPTION
**Pull request by giansi**
This PR implements shortcodes abstraction:

added BaseShortcode abstract class to define a shortcode object
updated shortcode-core.php to register shortcodes placed under a specific folder, within a given namespace
removed addCenterHandler and addRawHandler and replaced by Raw and Center shortcode objects

### CODE REVIEW

**Comment by rhukster** [comment]
I appreciate your effort on this, and I see where your going now.  Couple of questions though.  

What is the use of the interface?  are there other classes other than the base class that would use it?

With your PR, you pretty much have to break out every shortcode into it's own class, making the whole process more complicated. I'm not a big fan of complexity for the sake of it, and it would make my shortcode plugin for example, much more complex and require many more files and classes.

Am i wrong in this?

**Comment by giansi** [comment]
I think moving away shortcodes from the main plugin class, makes it lighter and more easy to read, understand and maintain. The conseguence is that every shortcode must define its own implementation, reliefing the main plugin class from the responsabilility to define what a shortcode does.

Actually, if I want to see what's behind the raw shortcode, I have to dig the long main plugin class and look for the addRawHandler method. In the proposed structure, I will have a well identified object, saved in a clear path - Shortcodes/Raw -, that only requires to define the shortcode name, a twig template if required and a function that renders the template.

A developer, who wants to implement its own shortcode, is not required to deal with shortcodes handlers, because this responsability is delegated to shortcode-code plugin class. He is only required to define its own plugin where his shortcodes live. The plugin main class will inheriths from ShortcodeCorePlugin, then he will just call the register method and he's done. Next he can implement its own shortcode.

Now you have seven simple shortcodes in this plugin, which result in seven methods in main plugin class. Each time you need a new shortcode you must add a new method to this class, increasing its complexity. Yes, breaking out every shortcode into it's own class obvioulsy require many more files and classes but this implementation makes things more clear and ordered IMO and semplifies the life of other developers who wants to implement their own shortcodes.

The new Gravstrap plugin implements more than 30 new shortcodes and putting them all into my plugin class will result in a pain to read and maintain.

What it misses here is a method to autoload classes. I've already implemented it in my plugin class but I have not included it here yet because I expected a discussion about this PR, so I will add it at a later time if you agree with me.

**Comment by rhukster** [comment]
Ok here's thing thing.  I looked over your implementation and I like what your trying to do, I just didn't like the way you were doing it :)  I've implemented a similar abstraction but with a different approach.   However, my changes are **not backwards compatible**.

Here's you can see the changes: https://github.com/getgrav/grav-plugin-shortcode-core/compare/develop...feature/shortcode-abstraction

I've also refactored the ShortcodeUI plugin to use this new approach: https://github.com/getgrav/grav-plugin-shortcode-ui/tree/feature/shortcode-abstraction

Take a look and let me know what you think.  Basically I'm just breaking it up so you can create individual classes for each shortcode, or create one for a bunch of shortcodes.  Your choice really.  However, it makes use of a new `ShortCodeManager` class, and all shortcodes extend a `Shortcode` base class.

Most of the logic is in the ShortCodeManager, keeping the shortcode classes themselves nice, small and lean.

I think this is a better approach going forward as it makes the system more flexible and simpler to write shortcodes in general.  Also it means the actual plugin file is very small.  I'll merge this shortly but wanted to give you a heads up.  

I think your the only person that has a plugin that extends ShortcodeCore, so i'll definitely give you a heads up fore I release too.

**Comment by giansi** [comment]
Hi @rhukster, thank you. When you think of releasing this new version? Just asking because I need some time to adapt my plugin

**Comment by rhukster** [comment]
Probably tomorrow.. i'm off to bed now.  It only took me about 20 mins to convert my Shortcode UI plugin, but I know yours is bigger.

**Comment by giansi** [comment]
@rhukster I'm ready for the new release. Please, ping me when you release it. Thank you

**Comment by rhukster** [comment]
Will do, adding a new bit of functionality to the core (wont effect existing stuff).. when it's tested, will release.. probably be a few hours as i have to step out soon.

**Comment by giansi** [comment]
Ok. It would be awesome if you could posticipate until your late night (perhaps 8 or 9 hours from) so I can release mine in my earlier morning. Otherwise, for me, it's better now rather than posticipate to tomorrow. Thank you

**Comment by rhukster** [comment]
That's fine.. i'll do it then.

**Comment by rhukster** [comment]
This PR has been taken into account in the new Shortcode 2.0 rewrite.  Thanks!

**Pull request closed without merging**
